# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - uses: actions/checkout@v2
    - run: mkdir -p target/
    
    - uses: actions/upload-artifact@v2
      with:
       name: target/universityScheduleBot-1.0-SNAPSHOT.jar
       path: target/
  
  
  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2


    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
          name: universityScheduleBot-1.0-SNAPSHOT.jar
          path: target/
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run:  docker build . --file Dockerfile --tag my-image-name:$(date +%s)
